"""AP Mind: the dependency-free Hybrid Mind runtime nucleus."""

from .governance import GovernanceCompatibilityRecord
from .contracts import *  # noqa: F401,F403 - stable public contract surface
from .environment import EnvironmentAdapter, LocalVibeEnvironment
from .expression import (
    CallableExpressionRenderer,
    ExpressionRenderer,
    RendererDecision,
    RendererProposal,
    review_renderer_proposal,
)
from .gateway import (
    CallableGateway,
    GatewayCallReceipt,
    GatewayProposal,
    GatewayTransportError,
    HybridGateway,
    ModelTransport,
    NullGateway,
    OfflineTeacherGateway,
    OpenAICompatibleGateway,
    UrllibModelTransport,
)
from .mind_state import ContinuityState
from .knowledge_correction import (
    CHANGE_OPERATIONS,
    CorrectionInterpretation,
    KnowledgeCorrectionConflict,
    KnowledgeCorrectionDraft,
    KnowledgeCorrectionInterpreter,
    KnowledgeCorrectionNotFound,
    KnowledgeCorrectionRequest,
    KnowledgeCorrectionStore,
    KnowledgeSectionChange,
    NullKnowledgeCorrectionInterpreter,
    OpenAICompatibleKnowledgeCorrectionInterpreter,
    apply_section_changes,
)
from .logic_field import (
    EXTRACTOR_VERSION,
    LOGIC_FIELD_VERSION,
    LogicEdge,
    LogicFieldInstrument,
    LogicFieldPolicy,
    LogicFieldReport,
    LogicNode,
    LogicQuery,
    SourceSnapshot,
)
from .codex_activity import (
    CodexJsonlReceptor,
    CodexSampleBatch,
    CodexVisibleOccurrence,
)
from .output import (
    CallableExpressionReadbackAnnotator,
    ExpressionReadbackAnnotator,
    LocalTextUnitActuator,
    OutputCursor,
    OutputUnitResult,
    TextUnitActuator,
    annotate_output_readback,
    apply_output_revision,
    dispatch_next_unit,
    output_control_result,
    output_revision_is_recoverable,
    output_revision_rejection_reasons,
    prepare_output,
    restore_output,
    set_output_status,
)
from .project_knowledge import (
    DEFAULT_BRIEF_CHARS,
    MAX_BRIEF_CHARS,
    MIN_BRIEF_CHARS,
    KnowledgeRevisionConflict,
    KnowledgeReviewEnvironment,
    KnowledgeReviewRequest,
    KnowledgeReviewRun,
    LocalKnowledgeRevision,
    ProjectKnowledgeStore,
    run_knowledge_review_episode,
)
from .runtime import MindRuntime
from .runtime_types import *  # noqa: F401,F403
from .storage import EventStore
from .studio_demo import StudioEpisodeRequest, StudioTextEnvironment, run_studio_episode
from .studio_projection import EpisodeView, STUDIO_PROJECTION_VERSION, project_episode, project_tick
from .studio_server import StudioEpisodeService, StudioRequestConflict, create_server
from .vibe import (
    UrllibVibeTransport,
    VibeEnvironment,
    VibePage,
    VibeProjectClient,
    VibeRuntimeDriver,
    VibeSyncReport,
    VibeTransport,
    VibeTransportError,
)
from .vibe_mind import (
    CurriculumAttempt,
    CurriculumCandidate,
    CurriculumEpisodeRun,
    CurriculumOutcome,
    FeedbackEpisodeRun,
    FeedbackLesson,
    ProjectActivity,
    ProjectCognitionEnvironment,
    ProjectEpisodeRun,
    ProjectFeedback,
    ProjectKnowledgeProposal,
    ProjectLearningLedger,
    curricula_from_teacher_frame,
    lesson_from_feedback,
    proposal_from_activity,
    run_curriculum_episode,
    run_feedback_episode,
    run_project_episode,
)
from .vibe_projection import (
    AP_VIBE_PROJECTION_VERSION,
    ProjectEpisodeView,
    project_activity_run,
    project_feedback_run,
    project_knowledge_review_run,
)

__all__ = [
    "GovernanceCompatibilityRecord",
    "EnvironmentAdapter",
    "LocalVibeEnvironment",
    "RendererDecision",
    "RendererProposal",
    "ExpressionRenderer",
    "CallableExpressionRenderer",
    "review_renderer_proposal",
    "CallableGateway",
    "GatewayCallReceipt",
    "GatewayProposal",
    "GatewayTransportError",
    "HybridGateway",
    "ModelTransport",
    "NullGateway",
    "OfflineTeacherGateway",
    "OpenAICompatibleGateway",
    "UrllibModelTransport",
    "ContinuityState",
    "CHANGE_OPERATIONS",
    "CorrectionInterpretation",
    "KnowledgeCorrectionConflict",
    "KnowledgeCorrectionDraft",
    "KnowledgeCorrectionInterpreter",
    "KnowledgeCorrectionNotFound",
    "KnowledgeCorrectionRequest",
    "KnowledgeCorrectionStore",
    "KnowledgeSectionChange",
    "NullKnowledgeCorrectionInterpreter",
    "OpenAICompatibleKnowledgeCorrectionInterpreter",
    "apply_section_changes",
    "EXTRACTOR_VERSION",
    "LOGIC_FIELD_VERSION",
    "LogicEdge",
    "LogicFieldInstrument",
    "LogicFieldPolicy",
    "LogicFieldReport",
    "LogicNode",
    "LogicQuery",
    "SourceSnapshot",
    "CodexJsonlReceptor",
    "CodexSampleBatch",
    "CodexVisibleOccurrence",
    "TextUnitActuator",
    "ExpressionReadbackAnnotator",
    "CallableExpressionReadbackAnnotator",
    "OutputCursor",
    "OutputUnitResult",
    "prepare_output",
    "restore_output",
    "set_output_status",
    "apply_output_revision",
    "annotate_output_readback",
    "output_control_result",
    "output_revision_is_recoverable",
    "output_revision_rejection_reasons",
    "dispatch_next_unit",
    "LocalTextUnitActuator",
    "MIN_BRIEF_CHARS",
    "DEFAULT_BRIEF_CHARS",
    "MAX_BRIEF_CHARS",
    "KnowledgeRevisionConflict",
    "KnowledgeReviewRequest",
    "LocalKnowledgeRevision",
    "KnowledgeReviewRun",
    "ProjectKnowledgeStore",
    "KnowledgeReviewEnvironment",
    "run_knowledge_review_episode",
    "MindRuntime",
    "EventStore",
    "EpisodeView",
    "STUDIO_PROJECTION_VERSION",
    "project_episode",
    "project_tick",
    "StudioEpisodeRequest",
    "StudioTextEnvironment",
    "run_studio_episode",
    "StudioEpisodeService",
    "StudioRequestConflict",
    "create_server",
    "VibeEnvironment",
    "VibePage",
    "VibeProjectClient",
    "VibeRuntimeDriver",
    "VibeSyncReport",
    "VibeTransport",
    "VibeTransportError",
    "UrllibVibeTransport",
    "ProjectActivity",
    "ProjectFeedback",
    "CurriculumCandidate",
    "CurriculumAttempt",
    "CurriculumOutcome",
    "CurriculumEpisodeRun",
    "FeedbackLesson",
    "ProjectLearningLedger",
    "ProjectKnowledgeProposal",
    "ProjectCognitionEnvironment",
    "ProjectEpisodeRun",
    "FeedbackEpisodeRun",
    "curricula_from_teacher_frame",
    "lesson_from_feedback",
    "proposal_from_activity",
    "run_curriculum_episode",
    "run_feedback_episode",
    "run_project_episode",
    "AP_VIBE_PROJECTION_VERSION",
    "ProjectEpisodeView",
    "project_activity_run",
    "project_feedback_run",
    "project_knowledge_review_run",
]
