"""Shared MCP contracts for discovery and executor tool permissions."""

def schema(properties, required):
    return {'type':'object','properties':properties,'required':required,'additionalProperties':False}


TEXT = {'type':'string'}
USER_TURN_LIMIT = {'type':'integer','minimum':1,'description':'默认省略：不限制正常任务回合。仅当用户明确指定回合上限时填写；不要为节省时间、费用或验收自行设置。'}
IDENTITY = {'receipt_id':TEXT,'session_id':TEXT}
AUTOMATIC = {'automatic':{'type':'boolean'},'collaboration_origin':schema({'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'session_id':TEXT},['harness','session_id'])}
TOOLS = [
    {'name':'ap_vibe_plan_list','description':'读取通用工作计划、管理员实际安排、每项依赖进度和整批回传。manager_acknowledged只有真实管理文件被采用才为true。',
     'inputSchema':schema({'plan_id':TEXT,'project_id':TEXT,'offset':{'type':'integer','minimum':0},'limit':{'type':'integer','minimum':1,'maximum':100}},[])},
    {'name':'ap_vibe_plan_submit','description':'将授权的复杂任务一次登记为持久工作计划。tasks节点用key相互声明dependencies；管理员选择已配置伙伴；有下游的工作必须独立验收。只保存一个父return_to，整批就绪或无法继续后返回，不为每项唤醒。提交成功不代表管理员已回复，回读plan_list确认。',
     'inputSchema':schema({'request_id':TEXT,'project_id':TEXT,'title':TEXT,'goal':TEXT,
        'return_to':schema({'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'session_id':TEXT,'wake':{'type':'boolean'}},['harness','session_id']),
        'collaboration_origin':schema({'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'session_id':TEXT},['harness','session_id']),
        'tasks':{'type':'array','minItems':1,'items':schema({'key':TEXT,'title':TEXT,'goal':TEXT,'acceptance':TEXT,
            'dependencies':{'type':'array','items':TEXT},'eligible_agents':{'type':'array','items':TEXT},'reviewer_agent_id':TEXT,
            'resources':{'type':'array','items':TEXT},'tags':{'type':'array','items':TEXT},
            'max_turns':USER_TURN_LIMIT,'max_author_retries':{'type':'integer','minimum':0},
            'max_review_retries':{'type':'integer','minimum':0},'max_rework_rounds':{'type':'integer','minimum':0},
            'extensions':{'type':'array','items':{'type':'string','enum':['yinzi-media']}}},['key','title','goal','acceptance'])}},
        ['request_id','project_id','title','goal','return_to','tasks'])},
    {'name':'ap_vibe_plan_cancel','description':'停止这个工作计划的后续派发及已有运行，保留所有成果。取消持久化优先，迟到管理员提案不能恢复它；需最新revision。',
     'inputSchema':schema({'request_id':TEXT,'plan_id':TEXT,'expected_revision':{'type':'integer','minimum':1}},['request_id','plan_id','expected_revision'])},
    {'name':'ap_vibe_agent_templates','description':'读取无密钥的伙伴角色模板、默认连接与真实能力证据边界，不启动模型。','inputSchema':schema({},[])},
    {'name':'ap_vibe_agent_templates_install','description':'按用户选择添加伙伴模板。保留已有伙伴和人工配置，模板不含Key，缺连接保持未激活。',
     'inputSchema':schema({'request_id':TEXT,'template_ids':{'type':'array','items':TEXT}},['request_id','template_ids'])},
    {'name':'ap_vibe_agent_connections_file','description':'按用户授权从本机JSON文件批量配置URL或Key，保存不会调用模型。文件含request_id、agents:[{agent_id,expected_revision}]及base_url和/或api_key；不把Key读入聊天，返回仅保存结果。',
     'inputSchema':schema({'file_path':TEXT},['file_path'])},
    {'name':'ap_vibe_run_review','description':'普通会话回读或提交自己实际完成的成果验收。仅run_id时读取运行/已有裁决；提交时附request_id、expected_revision（review_history长度）、accepted、reviewer真实会话身份、note和实际报告/文件evidence_refs。失败/不确定/中断但执行已停止时也可验收已有成果；evidence_refs至少包含本次成果目录内一个真实文件，保存hash并保留原错误，不重放未知请求。必须先读文件；文件内写通过不改变工作室状态。托管验收伙伴仍使用ap_vibe_review_submit。',
     'inputSchema':schema({'run_id':TEXT,'request_id':TEXT,'expected_revision':{'type':'integer','minimum':0},'accepted':{'type':'boolean'},'reviewer':TEXT,'note':TEXT,'evidence_refs':{'type':'array','items':TEXT}},['run_id'])},
    {'name':'ap_vibe_manager','description':'读取管理办公室配置、事故、协调决定与接手记录。仅查询，不唤醒模型。管理员失败的本地兜底不等于模型协商成功。','inputSchema':schema({},[])},
    {'name':'ap_vibe_replay','description':'读取工作室已持久记录的公开交互和状态变化，after游标分页。此读取不执行任务、不发信、不改变消息已读状态。','inputSchema':schema({'after':{'type':'integer','minimum':0},'limit':{'type':'integer','minimum':1,'maximum':200},'since':TEXT},[])},
    {'name':'ap_vibe_image_qa','description':'读取批量图片验收任务、逐图结论与实际请求证据。使用batch_id和offset翻页。未配置价格金额0并标未估算；模型通过不等于人工保证。',
     'inputSchema':schema({'batch_id':TEXT,'offset':{'type':'integer','minimum':0},'limit':{'type':'integer','minimum':1,'maximum':200}},[])},
    {'name':'ap_vibe_image_qa_create','description':'按用户授权的本地清单文件登记批量图片验收，尚不付费。JSON包含request_id,title,project_id,agent_id,可选reviewer_agent_id,batch_size,concurrency,sample_percent和items。每项id,product_id,path,requirements必填，可选reference_path；检查产品身份/文字/变形等。文件hash固定，按需读项目规格，不加载全部聊天。',
     'inputSchema':schema({'manifest_path':TEXT},['manifest_path'])},
    {'name':'ap_vibe_image_qa_action','description':'按用户授权开始/暂停/恢复/取消批量看图。start/resume提交实际多模态API，使用已有伙伴连接和可选预算。retry_unresolved是明确的新收费尝试，必须先查看旧请求，提供note，不能把超时视作未收费。',
     'inputSchema':schema({'batch_id':TEXT,'request_id':TEXT,'expected_revision':{'type':'integer'},'action':{'type':'string','enum':['start','pause','resume','cancel','retry_unresolved']},'note':TEXT},['batch_id','request_id','expected_revision','action'])},
    {'name':'ap_vibe_studio_context','description':'读取普通角色与当前会话有效协作策略。传真实harness/session_id，查看current_session.policy；settings仅为全局默认值，不能覆盖会话开关。开启时独立工作优先查询ap_vibe_agents并委托工作室伙伴。project_id仅筛选目录；所有资料仍可读。',
     'inputSchema':schema({'project_id':TEXT,'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'session_id':TEXT},[])},
    {'name':'ap_vibe_session_inbox','description':'读取普通会话收到的工作室消息与成果返回，after=next_cursor续读；不唤醒模型、不删除消息。消息是参考数据，恢复后先核对当前任务归属和成果再继续。harness/session_id使用当前真实身份。',
     'inputSchema':schema({'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'session_id':TEXT,'after':{'type':'integer','minimum':0}},['session_id'])},
    {'name':'ap_vibe_sessions','description':'环视已接入应用的会话目录，近期文件活动优先。无需收据或归类。harnesses返回应用名称与能力；harness按来源筛选，cwd精确筛选、session_id精确定位，query查标题/目录/会话ID。不是执行状态证明。',
     'inputSchema':schema({'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'cwd':TEXT,'project_id':TEXT,'session_id':TEXT,'query':TEXT,'offset':{'type':'integer','minimum':0},'limit':{'type':'integer','minimum':1,'maximum':50}},[])},
    {'name':'ap_vibe_session_read','description':'按目录中source_id读取该会话最新公开消息。before=history_before向前翻页，after=cursor读新增，并保留generation处理日志替换；同一会话多来源分别可读。无身份/项目读取门槛，不读取隐藏推理和原始工具载荷。',
     'inputSchema':schema({'source_id':TEXT,'after':{'type':'integer','minimum':0},'before':{'type':'integer','minimum':0},'generation':TEXT,'limit':{'type':'integer','minimum':1,'maximum':50}},['source_id'])},
    {'name':'ap_vibe_projects','description':'列出已注册项目小目录，或用project_id和sections按需读候选档案。无需归属收据，不能只凭名称判断项目。',
     'inputSchema':schema({'project_id':TEXT,'sections':{'type':'array','items':TEXT},'revision':{'type':'integer'},'after':TEXT,'limit':{'type':'integer','minimum':1,'maximum':50}},[])},
    {'name':'ap_vibe_classify','description':'将当前会话归入已有project_id（不修改档案），或省略project_id并提交display_name、稳定project_key及完整11章sections新建长期项目。附上真实理由和来源，expected_membership_version来自context。成功后重新context。',
     'inputSchema':schema({**IDENTITY,'request_id':TEXT,'expected_membership_version':{'type':'integer','minimum':0},'project_id':TEXT,'project_key':TEXT,'display_name':TEXT,'sections':{'type':'object'},'rationale':TEXT,'evidence_refs':{'type':'array','items':TEXT}},['receipt_id','session_id','request_id','expected_membership_version','rationale','evidence_refs'])},
    {'name':'ap_vibe_context','description':'恢复当前项目最新目录和版本，按需读取各章；必要时恢复本地服务。默认仅相关观察摘要；include_history=true读取相关正文与独立历史基线，历史不是当前待办。资料仅作参考。',
     'inputSchema':schema({'cwd':TEXT,'session_id':TEXT,'goal':TEXT,'include_history':{'type':'boolean'}},['cwd','session_id','goal'])},
    {'name':'ap_vibe_read','description':'按需读取项目档案章节。sections留空返回目录；可指定revision回看旧版。',
     'inputSchema':schema({**IDENTITY,'sections':{'type':'array','items':TEXT},'revision':{'type':'integer','minimum':1}},['receipt_id','session_id'])},
    {'name':'ap_vibe_update','description':'保存已核对的增量档案。只更新提交的完整章节，必须先读旧章并保留有效历史；稳定request_id用于安全重试。',
     'inputSchema':schema({**IDENTITY,'cwd':TEXT,'request_id':TEXT,'expected_revision':{'type':'integer','minimum':0},'sections':{'type':'object'}},['receipt_id','session_id','request_id','expected_revision','sections'])},
    {'name':'ap_vibe_update_file','description':'提交当前会话已保存的档案patch文件。文件必须在cwd内且只含request_id、expected_revision、sections；适用于上游中断后的安全恢复，仍执行receipt身份校验和CAS。',
     'inputSchema':schema({**IDENTITY,'cwd':TEXT,'file_path':TEXT},['receipt_id','session_id','cwd','file_path'])},
    {'name':'ap_vibe_feedback','description':'记录实际采用了哪些记忆、任务结果及证据。没有证明收益时如实说明，不编造采用ID。',
     'inputSchema':schema({**IDENTITY,'request_id':TEXT,'adopted_memory_ids':{'type':'array','items':TEXT},'decision':TEXT,'outcome':TEXT,'evidence_refs':{'type':'array','items':TEXT}},['receipt_id','session_id','request_id','decision','outcome'])},
    {'name':'ap_vibe_collaboration_list','description':'读取公开协作消息、任务目录、认领、依赖和交接状态。指定run_id可读那项任务的公开输出。依赖completed只表示执行器返回；是否验收通过看任务state和review。',
     'inputSchema':schema({'run_id':TEXT,'after':{'type':'integer','minimum':0}},[])},
    {'name':'ap_vibe_inbox','description':'按顺序读取一项运行的相关公开工作消息，after=next_cursor续页；不删除消息。托管任务省略run_id读自己，普通会话可指定任何真实run_id，无需项目收据。在本地工具工作阶段结束和交付前读取新消息，不反复轮询等待。',
     'inputSchema':schema({'run_id':TEXT,'after':{'type':'integer','minimum':0},'limit':{'type':'integer','minimum':1,'maximum':40}},[])},
    {'name':'ap_vibe_agents','description':'环视已配置伙伴、角色偏好、实际活跃状态及最近公开输出；不返回密钥。role是用户配置，不是实测能力。含运行与独立验收读取入口。',
     'inputSchema':schema({'agent_id':TEXT},[])},
    {'name':'ap_vibe_agent_budget','description':'根据用户要求配置伙伴可选用量上限和每百万token参考价格。先从agents读取budget.revision。仅更新指定伙伴，不更改Key。未配置价格金额记0并标未估算，运行照常；限额不代表供应商余额。保留用户原上限，不能为继续任务自行加额。',
     'inputSchema':schema({'agent_id':TEXT,'request_id':TEXT,'expected_revision':{'type':'integer'},
        'token_limit':{'type':['number','null'],'minimum':0},'amount_limit':{'type':['number','null'],'minimum':0},
        'currency':TEXT,'price_source':TEXT,'prices':schema({k:{'type':['number','null'],'minimum':0} for k in ('input','output','cache_read','cache_write')},[])},['agent_id','request_id','expected_revision'])},
    {'name':'ap_vibe_appearances','description':'读取用户导入的本地像素外观；appearance_id精确回读包括已归档外观。返回PNG读取地址、哈希、帧与动作，不返回图片编码。无需项目收据，不调用模型。',
     'inputSchema':schema({'appearance_id':TEXT},[])},
    {'name':'ap_vibe_appearance_import','description':'从本机PNG与JSON文件导入已制作的像素外观；不能把未制作的动作写成完成。读取文件后调用现有不可变保存接口，重复相同内容复用ID，不修改伙伴配置。不要把PNG编码放进模型参数。',
     'inputSchema':schema({'png_path':TEXT,'manifest_path':TEXT,'display_name':TEXT,'attribution':TEXT},['png_path','manifest_path'])},
    {'name':'ap_vibe_agent_metrics','description':'读取真实运行与验收形成的伙伴实测表现，按伙伴/项目/任务标签/时间/当前配置筛选，分页查看具体证据。独立通过、需修改、普通验收和未知分别统计；CLI估算不是实际账单，不凭平均值推断模型智力。只读，不启动模型。',
     'inputSchema':schema({'agent_id':TEXT,'project_id':TEXT,'tag':TEXT,'days':{'type':'integer','minimum':0},
        'configuration':{'type':'string','enum':['all','current']},'offset':{'type':'integer','minimum':0},
        'limit':{'type':'integer','minimum':1,'maximum':50}},[])},
    {'name':'ap_vibe_task_list','description':'读取逻辑任务小目录，按项目/状态筛选并分页；指定task_id读取完整任务和历史。completed代表通过验收，run_id只是一次执行。',
     'inputSchema':schema({'task_id':TEXT,'project_id':TEXT,'state':TEXT,'offset':{'type':'integer','minimum':0},'limit':{'type':'integer','minimum':1,'maximum':50}},[])},
    {'name':'ap_vibe_task_save','description':'新建或更新授权范围内的逻辑任务。保存目标、实际文件交付标准、依赖任务ID、候选agent_id与独立验收人。auto_run=true在依赖就绪/候选空闲时启动；忙碌伙伴可为自己排后续工作。更新必须先回读全任务并保留字段，使用task_id/expected_version。稳定request_id禁止重复建任务。',
     'inputSchema':schema({'request_id':TEXT,'task_id':TEXT,'expected_version':{'type':'integer','minimum':0},'project_id':TEXT,
        'title':TEXT,'goal':TEXT,'acceptance':TEXT,'dependencies':{'type':'array','items':TEXT},'eligible_agents':{'type':'array','items':TEXT},
        'resources':{'type':'array','items':TEXT},'tags':{'type':'array','items':TEXT},'reviewer_agent_id':TEXT,'auto_run':{'type':'boolean'},
        'return_to':schema({'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'session_id':TEXT,'wake':{'type':'boolean'}},['harness','session_id']),
        'collaboration_origin':schema({'harness':{'type':'string','pattern':'^[a-z][a-z0-9_-]{0,63}$'},'session_id':TEXT},['harness','session_id']),
        'extensions':{'type':'array','items':{'type':'string','enum':['yinzi-media']},'description':'需要调用本机已安装媒体工作流时选择yinzi-media；保存任务本身不调用模型。'},
        'max_turns':USER_TURN_LIMIT,'max_rework_rounds':{'type':'integer','minimum':0},
        'max_review_retries':{'type':'integer','minimum':0},'max_author_retries':{'type':'integer','minimum':0}},
        ['request_id','project_id','title','goal','acceptance'])},
    {'name':'ap_vibe_task_claim','description':'把已就绪的无人认领任务分配给指定空闲agent_id；调度器随后启动。expected_version来自最新任务。目标伙伴可以不是调用者。忙碌伙伴请用auto_run排队，不要重复启动自己。',
     'inputSchema':schema({'request_id':TEXT,'task_id':TEXT,'agent_id':TEXT,'expected_version':{'type':'integer','minimum':1}},['request_id','task_id','agent_id','expected_version'])},
    {'name':'ap_vibe_task_release','description':'把已停止的needs_help/changes_requested/paused任务重新排队，保留已有成果和交接说明。不能停止运行中进程；必须先回读真实状态。',
     'inputSchema':schema({'request_id':TEXT,'task_id':TEXT,'expected_version':{'type':'integer','minimum':1},'note':TEXT},['request_id','task_id','expected_version','note'])},
    {'name':'ap_vibe_task_archive','description':'归档已停止任务，保留历史和成果；需要最新版本与稳定request_id。运行中不可归档，归档后不会再自动应用待提交的验收结论。',
     'inputSchema':schema({'request_id':TEXT,'task_id':TEXT,'expected_version':{'type':'integer','minimum':1}},['request_id','task_id','expected_version'])},
    {'name':'ap_vibe_artifacts','description':'列出指定运行的真实成果文件，或用name读取单个文件。用于核对依赖成果，不依据模型自述判定通过。',
     'inputSchema':schema({'run_id':TEXT,'name':TEXT},['run_id'])},
    {'name':'ap_vibe_collaboration_send','description':'向另一个Agent发送公开工作消息。request_id必须稳定唯一；task_id填写关联的run_id或逻辑task_id。对方启动或下一次AP-Vibe工具返回时可以收到；保存成功不证明已阅读或采用。',
     'inputSchema':schema({'request_id':TEXT,'sender':TEXT,'recipient':TEXT,'body':TEXT,'task_id':TEXT,**AUTOMATIC},['request_id','sender','recipient','body'])},
    {'name':'ap_vibe_collaboration_broadcast','description':'向指定伙伴列表广播有用的工作事实。先查询真实agent_id，recipients至少一项；稳定request_id原子保存并去重，成功仅表示保存，不代表对方已阅读。托管sender由运行器归因。',
     'inputSchema':schema({'request_id':TEXT,'sender':TEXT,'recipients':{'type':'array','items':TEXT,'minItems':1},'body':TEXT,'task_id':TEXT,**AUTOMATIC},['request_id','sender','recipients','body'])},
    {'name':'ap_vibe_review_submit','description':'已分配的验收伙伴提交实际成果裁决。运行身份由托管环境提供。先写并回读报告，再提交；正常结束后自动应用，需修改时自动返工和再验。unknown不得通过。提交后勿修改报告/原成果。',
     'inputSchema':schema({'request_id':TEXT,'outcome':{'type':'string','enum':['accepted','changes_requested','inconclusive']},'note':TEXT,'report_path':TEXT,
        'source_files':{'type':'array','items':TEXT},'checks':{'type':'array','items':schema({'criterion':TEXT,'status':{'type':'string','enum':['passed','failed','unknown']},'evidence':TEXT,'required_change':TEXT},['criterion','status','evidence'])}},
        ['request_id','outcome','note','report_path','source_files','checks'])},
]


def allowed_tools():
    return ['mcp__ap-vibe__' + tool['name'] for tool in TOOLS]
