import {useEffect,useRef,useState} from 'react';

const labels={draft:'尚未开始',running:'正在验收',paused:'已暂停',cancelled:'已取消',completed:'验收结束',needs_attention:'有图片需要处理',pending:'排队中',review_pending:'等待复核',passed:'通过',rejected:'不通过',needs_review:'需要复核',uncertain:'请求结果未知',error:'未能判定'};
async function api(path='',payload){
  const r=await fetch('/v1/ap-vibe/studio/image-qa'+path,{method:payload?'POST':'GET',headers:{'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});
  const value=await r.json();if(!r.ok||value.ok===false)throw new Error(value.error?.message||value.error?.code||'图片验收请求未完成');return value;
}
export function BatchImageQA({agents,projects,onAddAgent}){
  const [batches,setBatches]=useState([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState(null),[page,setPage]=useState(0);
  const [form,setForm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [loaded,setLoaded]=useState(false),[manual,setManual]=useState(null),[preview,setPreview]=useState(null);
  const previewDialog=useRef(null);
  useEffect(()=>{if(preview)previewDialog.current?.showModal();},[preview]);
  const pending=useRef(null);
  const draft=useRef(null);
  const available=agents.filter(a=>!a.archived&&a.auth_mode!=='local_login');
  useEffect(()=>{let active=true,timer;async function poll(){try{const v=await api();if(active){setBatches(v.batches);setLoaded(true);setSelected(old=>old||v.batches[0]?.batch_id||'');}}catch(e){if(active)setError(e.message);}if(active)timer=setTimeout(poll,5000);}poll();return()=>{active=false;clearTimeout(timer);};},[]);
  useEffect(()=>{if(!selected)return;let active=true,timer;async function poll(){try{const v=await api('?'+new URLSearchParams({batch_id:selected,offset:page*50,limit:50}));if(active){setDetail(v);setError('');}}catch(e){if(active)setError(e.message);}if(active)timer=setTimeout(poll,3000);}poll();return()=>{active=false;clearTimeout(timer);};},[selected,page]);
  const current=detail?.batches?.[0];
  async function create(e){e.preventDefault();const signature=JSON.stringify(form);if(pending.current?.signature!==signature)pending.current={signature,id:crypto.randomUUID(),start:crypto.randomUUID()};setBusy(true);setError('');try{
    const v=await api('/create',{...form,request_id:pending.current.id,reviewer_agent_id:form.reviewer_agent_id||null});
    await api('/action',{batch_id:v.batch_id,request_id:pending.current.start,expected_revision:1,action:'start'});
    setSelected(v.batch_id);setPage(0);setDetail(null);setForm(null);draft.current=null;pending.current=null;setNotice(`已登记 ${v.item_count} 张图片。后台逐批验收，你可以离开页面。`);
  }catch(e){setError(e.message);}finally{setBusy(false);}}
  async function act(action){setBusy(true);setError('');try{const v=await api('/action',{batch_id:current.batch_id,request_id:crypto.randomUUID(),expected_revision:current.revision,action});setDetail(old=>({...old,batches:[{...current,...v}]}));setNotice(v.inflight);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function resolve(e){e.preventDefault();setBusy(true);setError('');try{await api('/resolve',manual);setManual(null);setDetail(await api('?'+new URLSearchParams({batch_id:selected,offset:page*50,limit:50})));setNotice('人工判定已保存，原模型意见仍保留。');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function exportCSV(){setBusy(true);try{let offset=0,rows=[];do{const v=await api('?'+new URLSearchParams({batch_id:selected,offset,limit:200}));rows.push(...v.items);offset=v.next_offset;}while(offset!=null);
    const cell=v=>'"'+String(v??'').replace(/^[=+\-@\t\r]/,"'$&").replaceAll('"','""')+'"';
    const csv=[['图片ID','产品','状态','文件','结论依据','模型','请求ID'],...rows.map(i=>{const h=i.history?.at(-1)||{};return [i.id,i.product_id,labels[i.state]||i.state,i.image.path,h.reason||i.error||'',h.model||'',h.request_id||i.active_request||''];})].map(r=>r.map(cell).join(',')).join('\r\n');
    const href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=href;a.download='图片验收-'+selected+'.csv';a.click();setNotice(`已生成 ${rows.length} 张图片的结果文件，请在浏览器下载中查看。`);setTimeout(()=>URL.revokeObjectURL(href),1000);
  }catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section className="page-section batch-qa" aria-label="批量图片验收">
    <div className="task-board-head"><div><span className="eyebrow">电商与素材检查</span><h2>几千张图，让合适的伙伴逐批检查</h2><p className="muted">普通问题批量处理；看不清、风险较高和抽检图片交给复核伙伴。每张图都有自己的记录。</p></div><button className="primary-button" onClick={()=>{setError('');const saved=draft.current;setForm(saved?{...saved,agent_id:available.some(a=>a.agent_id===saved.agent_id)?saved.agent_id:available[0]?.agent_id||''}:{title:'产品图片验收',directory:'',product_id:'',requirements:'',reference_path:'',project_id:'',agent_id:available[0]?.agent_id||'',reviewer_agent_id:'',batch_size:4,concurrency:2,sample_percent:10});}}>＋ 验收一批图片</button></div>
    <div className="batch-help"><b>最省事的用法</b><p>直接对 Codex 说：“请用工作室里合适的多模态伙伴，检查 D:\产品图。对照参考图，找出变形、错字和错色，拿不准的交给复核伙伴。”</p><small>伙伴须实际支持图片输入；通常先用少量代表样本校准。图片会发送到所选伙伴配置的 API，可能产生费用。这里的批量执行器只发送图片和检查标准，不重复载入编程会话。</small></div>
    {error&&<p className="agent-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="task-board-grid"><div className="task-list">{batches.map(b=><button key={b.batch_id} className={selected===b.batch_id?'selected':''} onClick={()=>{setSelected(b.batch_id);setPage(0);setDetail(null);}}><strong>{b.title}</strong><span>{labels[b.state]} · {b.total} 张</span></button>)}{!loaded?<p role="status">正在读取图片批次…</p>:!batches.length&&<p>还没有图片验收任务。可直接交给 Codex，也可以点上方按钮。</p>}</div>
    <div className="task-detail">{!current?<p>{selected?'正在读取逐图结果…':'选择一批图片查看结果。'}</p>:<><div className="agent-output-head"><div><h3>{current.title}</h3><span>{labels[current.state]}</span></div><button disabled={busy} onClick={exportCSV}>导出全部结果 CSV</button></div>
      <div className="batch-counts">{Object.entries(current.counts).map(([key,n])=><span key={key}>{labels[key]||key}<b>{n}</b></span>)}</div>
      <progress value={current.total-(current.counts.pending||0)-(current.counts.review_pending||0)-(current.counts.running||0)} max={current.total||1}/>
      <p className="batch-cost-status"><strong>{current.budget?.price_status==='estimated'?'按请求时价格估算，不是实际账单':'金额未估算，不代表免费；实际费用以服务商账单为准。'}</strong></p>
      <p className="muted">本批已知用量 {Number(current.usage?.known_tokens||0).toLocaleString()} token · 本地金额记录 {Object.entries(current.usage?.amounts_by_currency||{CNY:0}).map(([currency,n])=>`${currency} ${Number(n).toFixed(4)}`).join(' / ')||'CNY 0.0000'}{current.budget?.price_status!=='estimated'?'（未配置价格）':''}{current.usage?.unknown_usage_requests>0?` · ${current.usage.unknown_usage_requests} 次请求尚无用量数据`:''}{current.budget?.exhausted?' · 等待投喂，排队图片保留':''}</p>
      <div className="agent-actions">{current.state==='draft'&&<button disabled={busy} onClick={()=>act('start')}>开始这批验收</button>}{current.state==='running'&&<button disabled={busy} onClick={()=>act('pause')}>暂停新增请求</button>}{['paused','needs_attention'].includes(current.state)&&(current.counts.pending||current.counts.review_pending)>0&&<button disabled={busy} onClick={()=>act('resume')}>继续未提交的图片</button>}{!['cancelled','completed'].includes(current.state)&&<button disabled={busy} onClick={()=>act('cancel')}>取消后续验收</button>}</div>
      {current.state==='needs_attention'&&<p>结果未知的请求不会自动重放。请让 Codex 按请求ID核对；确需再次尝试时明确说明，旧记录与可能发生的费用会保留。</p>}
      <div className="batch-results">{detail.items.map(i=><article key={i.id}><div><b>{i.id}</b><span className={'batch-verdict '+i.state}>{labels[i.state]||i.state}</span></div><small>{i.product_id} · {i.image.path}</small>{i.image.sha256&&<div className="batch-image-previews">{['image',...(i.reference?['reference']:[])].map(kind=>{const src='/v1/ap-vibe/studio/image-qa/image?'+new URLSearchParams({batch_id:selected,item_id:i.id,reference:String(kind==='reference')});return <button type="button" key={kind} onClick={()=>setPreview({item:i,batchId:selected})} title="放大对照原图"><img loading="lazy" src={src} alt={(kind==='reference'?'参考图':'待检查图片')+' '+i.id}/><span>{kind==='reference'?'参考图':'打开原图'}</span></button>;})}</div>}{i.history?.map((h,n)=><p key={h.request_id+':'+n}><b>{h.phase==='manual'?'人工判定':h.phase==='review'?'复核':'初审'} · {h.model||h.actor||(h.request_id?'模型请求':'本地检查')}：</b>{h.reason||h.error}</p>)}{i.error&&<p>{i.error}</p>}{!i.history?.length&&!i.error&&<p className="muted">等待此图的实际检查结果。</p>}{!['running','pending','review_pending'].includes(i.state)&&<button disabled={busy} onClick={()=>setManual({batch_id:selected,item_id:i.id,expected_version:i.version,request_id:crypto.randomUUID(),verdict:i.state==='rejected'?'rejected':i.state==='passed'?'passed':'',reason:''})}>记录人工复核</button>}</article>)}</div>
      <div className="office-pages"><button disabled={page===0} onClick={()=>setPage(page-1)}>上一页</button><span>第 {page+1} 页</span><button disabled={detail.next_offset==null} onClick={()=>setPage(page+1)}>下一页</button></div></>}</div></div>
    {preview&&<dialog ref={previewDialog} className="batch-preview-dialog" aria-label={'图片对照 '+preview.item.id} onClose={()=>setPreview(null)} onCancel={()=>setPreview(null)}>
      <div className="agent-output-head"><div><h2>图片对照 · {preview.item.id}</h2><p>{preview.item.requirements}</p></div><button type="button" autoFocus onClick={()=>setPreview(null)}>返回结果</button></div>
      <div className="batch-preview-large">{['image',...(preview.item.reference?['reference']:[])].map(kind=><figure key={kind}><figcaption>{kind==='image'?'待检查原图':'产品参考图'}</figcaption><img src={'/v1/ap-vibe/studio/image-qa/image?'+new URLSearchParams({batch_id:preview.batchId,item_id:preview.item.id,reference:String(kind==='reference')})} alt={(kind==='image'?'原图 ':'参考图 ')+preview.item.id}/></figure>)}</div>
      <p>原图仅在本机展示。按 Esc 或“返回结果”关闭，不会重新发起模型检查。</p>
    </dialog>}
    {manual&&<div className="agent-dialog-backdrop"><form className="agent-dialog" role="dialog" aria-modal="true" aria-label="人工复核图片" onSubmit={resolve}><h2>人工复核 · {manual.item_id}</h2><p>请先查看对应原图，再记录依据。会保留模型原判断，不触发新的API请求。</p><label>你的判定<select required value={manual.verdict} onChange={e=>setManual({...manual,verdict:e.target.value,request_id:crypto.randomUUID()})}><option value="" disabled>请选择你的判定</option><option value="passed">符合标准</option><option value="rejected">存在缺陷</option></select></label><label>看到的依据<textarea required rows={4} value={manual.reason} onChange={e=>setManual({...manual,reason:e.target.value,request_id:crypto.randomUUID()})}/></label><div className="agent-actions"><button type="button" disabled={busy} onClick={()=>setManual(null)}>返回</button><button className="primary-button" disabled={busy}>保存人工判定</button></div>{error&&<p role="alert">{error}</p>}</form></div>}
    {form&&<div className="agent-dialog-backdrop"><form className="agent-dialog" role="dialog" aria-modal="true" aria-label="登记图片验收" onSubmit={create}><div className="agent-output-head"><h2>告诉伙伴检查什么</h2><button type="button" disabled={busy} onClick={()=>setForm(null)}>×</button></div>
      <label>任务名称<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
      <label>图片文件夹的完整路径<input required placeholder="D:\商品A\待验收" value={form.directory} onChange={e=>setForm({...form,directory:e.target.value})}/></label><small>扫描 PNG、JPG 和 WebP，包含子目录。本表单适合一类产品；多 SKU 可让 Codex 建立分别带标准的清单。</small>
      <label>产品名称或 SKU<input required value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}/></label>
      <label>怎样算合格<textarea required rows={4} placeholder="例如：蓝色杯身，黑色杯盖，500 mL文字正确；无变形、裁切和多余物体。" value={form.requirements} onChange={e=>setForm({...form,requirements:e.target.value})}/></label>
      <label>参考图完整路径（可选）<input value={form.reference_path} onChange={e=>setForm({...form,reference_path:e.target.value})}/></label>
      <label>所属项目（可选）<select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">一次性验收，不归入项目</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.display_name}</option>)}</select></label>
      <label>初审伙伴<select required value={form.agent_id} onChange={e=>setForm({...form,agent_id:e.target.value})}>{available.map(a=><option key={a.agent_id} value={a.agent_id}>{a.name} · {a.model}</option>)}</select></label>
      {!available.length&&<div className="batch-help" role="status"><b>先添加一位支持图片输入的 API 伙伴</b><p>目前还没有可用于批量看图的连接。填写服务地址、Key 和模型即可；Codex 本机登录不能直接用作这里的图片 API。</p>{onAddAgent&&<button type="button" onClick={()=>{draft.current={...form};setForm(null);setNotice('验收草稿已保留。保存伙伴后，再点“验收一批图片”继续。');onAddAgent();}}>添加图片伙伴，保留草稿</button>}</div>}
      <label>复核伙伴（可选）<select value={form.reviewer_agent_id} onChange={e=>setForm({...form,reviewer_agent_id:e.target.value})}><option value="">暂不配置，疑难项保留待复核</option>{available.filter(a=>a.agent_id!==form.agent_id).map(a=><option key={a.agent_id} value={a.agent_id}>{a.name} · {a.model}</option>)}</select></label>
      <details><summary>批大小、并发和抽检</summary><label>每批图片数<input type="number" min="1" required value={form.batch_size} onChange={e=>setForm({...form,batch_size:Number(e.target.value)})}/></label><label>同时处理批数<input type="number" min="1" required value={form.concurrency} onChange={e=>setForm({...form,concurrency:Number(e.target.value)})}/></label><label>通过图片的抽检比例（%）<input type="number" min="0" max="100" required value={form.sample_percent} onChange={e=>setForm({...form,sample_percent:Number(e.target.value)})}/></label><small>先用小批校准，再按渠道能力提高并发。抽检和复核会有额外 API 用量。</small></details>
      <p className="muted">开始后会向配置的 API 发送这些图片。原图保留，缺失或损坏的文件单独记录，不影响其它图片。</p><button className="primary-button" disabled={busy||!available.length}>{busy?'正在登记与启动…':'登记并开始验收'}</button>
    </form></div>}
  </section>;
}
