import { useEffect, useState } from 'react';
import { workspaceApi } from './workspace-api';
import { MessageContent } from './MessageContent';
import { TeacherEvidence } from './TeacherEvidence';
import { CognitionEvidence } from './CognitionEvidence';

const NAMES = { flow: '流畅度', pressure: '压力', valence: '情感方向', arousal: '唤醒水平', fatigue: '疲劳', confidence: '信心', trust: '信任', tension: '紧张', curiosity: '好奇', frustration: '受挫', satisfaction: '满足', uncertainty: '不确定', novelty: '新颖性', interest: '兴趣' };
const FEELING_NAMES = { surprise: '惊讶', incongruity: '不协调感' };
const ACTION_NAMES = { stage_knowledge_candidate: '暂存待审项目知识', ask_user: '向用户确认', defer: '保留未闭合状态', observe_only: '仅记录这次活动', maintain_attention: '保持当前注意', diversify_attention: '分散注意，检查未绑定信息', shift_attention: '转移到相关记忆或范式' };
const actionName = (value) => ACTION_NAMES[value] || value || '未命名行动';
const feelingName = (value) => FEELING_NAMES[value] || NAMES[value] || value || '未命名感受';
const FEATURES = [['SA：当前感知', '把可见活动转成有来源的观察。', '输入不等于事实，未核对内容保留不确定性。'], ['感受与情绪慢量', '依据观察更新短期感受和较慢变化的内部量。', '这是可检查的计算状态，不是人类主观体验。'], ['行动器与行动节点', '候选进入同一个行动选择流程，执行后读取真实结果。', 'LLM 只能建议，不能越权执行动作。'], ['范式与学习', '把带证据的经验候选记录下来，在后续任务中检验。', '注册成功和一次测试通过，不等于长期学会。']];

export function CognitionPage({ state, project }) {
  const [report,setReport] = useState(null), [settings,setSettings] = useState(null), [error,setError] = useState('');
  const [editing,setEditing] = useState(false), [form,setForm] = useState({enabled:false,base_url:'',model:'',calls_per_hour:null,api_key:''});
  const [busy,setBusy] = useState(false), [message,setMessage] = useState(''), [frameIndex,setFrameIndex] = useState(0);
  useEffect(() => {
    let alive=true,timer;
    const poll=async()=>{const [r,s]=await Promise.allSettled([workspaceApi('organization/status'),workspaceApi('teacher/settings')]);if(alive){if(r.status==='fulfilled')setReport(r.value);if(s.status==='fulfilled')setSettings(s.value);setError([r,s].filter(item=>item.status==='rejected').map(item=>item.reason.message).join('；'));timer=setTimeout(poll,10000);}};
    poll(); return()=>{alive=false;clearTimeout(timer);};
  },[]);
  const episodes=state?.episodes || [];
  const episode=episodes.map(item=>item.episode || item.view || item).find(item=>item.ticks?.length);
  const frames=episode?.ticks || [],frame=frames[Math.min(frameIndex,frames.length-1)] || {};
  const slow=Object.entries(frame.slow_affect || {}).filter(([,value])=>typeof value==='number');
  const save=async()=>{setBusy(true);setError('');try{const result=await workspaceApi('teacher/settings',form);setSettings(result);setEditing(false);setForm(old=>({...old,api_key:''}));setMessage(result.message);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="page-stack cognition-page"><div className="page-header"><div><span className="eyebrow">AP 认知 · 可选特色</span><h1>看见一次观察，怎样成为下一步行动</h1><p>保留每一次感知、候选、选择与回读。用真实结果检验学习，而不是只看生成了多少文字。</p></div><span className="section-count">{settings === null ? '正在读取教师状态' : settings.enabled ? '外部教师已开启' : '基础模式 · 教师关闭'}</span></div>
    {error && <div className="notice-banner warn" role="alert">{error} 已读取的数据显示为上次状态。</div>}{settings?.error && <div className="notice-banner warn" role="alert">{settings.error}</div>}{message && <div className="notice-banner">{message}</div>}
    <div className="notice-banner warn cognition-cost-warning" role="note"><span className="cognition-cost-icon">!</span><div><strong>开启 AP 辅助认知前，请先了解成本与边界</strong><p>需要网络，并会产生外部 API 费用。大型项目可能约 <b>1 元/小时</b>，只是经验量级，不是固定报价；请求也可能变慢、失败或暂时回退基础模式。效果需要长期积累和对照记录才能判断，当前属于实验性质。关闭教师时，监看、项目档案、普通检索和 AP 本地运行时仍可使用。</p></div></div>
    <section className="cognition-hero"><div><span className="eyebrow">本地运行时 × 可选外部教师</span><h2>持续积累，逐步验证</h2><p>Codex 负责理解与整理项目，AP 管理有来源的认知过程、行动回读和后续检验。打开教师可获得更丰富的候选；收益需要在实际任务中测量。</p></div><div className="cognition-orbit" aria-label="感知、评价、行动和回读循环"><span>感知</span><span>评价</span><strong>AP<br/><small>真实回读</small></strong><span>行动</span><span>学习</span></div></section>
    <section className="page-section"><div className="organization-toolbar"><div><span className="eyebrow">按需开启</span><h2>AP 辅助认知核心</h2><p className="muted">不配置也能正常使用监看、项目档案、历史整理和按需检索。教师开启后，经过采样的活动才会请求外部模型。</p></div><button className="primary-button" disabled={settings === null} onClick={()=>{setForm({...settings,enabled:settings?.enabled || false,api_key:''});setEditing(true);}}>{settings === null ? '正在读取配置…' : '配置认知教师'}</button></div>
    <div className="mode-comparison"><article><b>基础模式</b><h3>简单、低成本、保留核心流程</h3><p>本地关键词检索与结构化章节恢复；AP 本地观察和行动回读继续工作。</p><p>没有外部教师生成的语义候选，复杂归因和跨场景泛化能力有限。历史整理仍使用你已登录的 Codex，计入 Codex 自身额度。</p></article><article><b>教师增强模式</b><h3>更丰富的候选，可检查的参与过程</h3><p>提供语义召回、预测、感受评价、范式、注意力与参数候选。多数候选先进入影子观察，不能直接改变认知；带后续结果的课程通过核验后才可参与学习。例如：把措辞不同但可能相关的旧决策列为召回候选，再核对它是否真的适用。</p><p>需要网络与 API 费用，可能出错或变慢；失败或达到你设置的预算时回退本地流程。提升幅度尚未独立测量。</p></article></div>
    <div className="knowledge-overview"><div><span>外部教师</span><strong>{settings === null ? '读取中' : settings.enabled ? '已开启' : '未开启'}</strong><small>{settings?.model || '尚未选择模型'}</small></div><div><span>本小时已尝试调用</span><strong>{settings?.attempts_this_hour ?? '…'} / {settings?.calls_per_hour == null ? '不限额' : settings.calls_per_hour}</strong><small>失败请求也会计入观测；费用以服务商账单为准。</small></div><div><span>多模态接入</span><strong>尚未接通</strong><small>当前教师收到结构化文本；选择多模态模型不等于已经处理图片或音频。</small></div></div>
    {editing && <form className="teacher-form" onSubmit={e=>{e.preventDefault();save();}}><label className="teacher-switch"><input type="checkbox" checked={!!form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>开启后允许将经过筛选的项目上下文发送到所配置服务商</label><label>OpenAI 兼容接口地址<input type="url" value={form.base_url || ''} onChange={e=>setForm({...form,base_url:e.target.value})} placeholder="https://你的服务商地址/v1"/></label><label>API Key<input type="password" autoComplete="off" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})} placeholder={settings?.key_saved?'已加密保存，留空保留原 Key':'填写你的 API Key'}/></label><label>模型名称<input value={form.model || ''} onChange={e=>setForm({...form,model:e.target.value})} placeholder="填写服务商实际提供的 API 模型 ID"/><small>建议优先评估 GPT‑5.6 系列的质量与成本。Sol / Terra 在 Codex 中的名称未必等于你的服务商 API 模型 ID，请以其模型列表为准。</small></label><label>可选的每小时预算<input type="number" min="1" step="1" value={form.calls_per_hour ?? ''} onChange={e=>setForm({...form,calls_per_hour:e.target.value === '' ? null : Number(e.target.value)})} placeholder="留空表示不限额"/><small>这是你主动设置的本地保护，不是 AP 必须的限制；留空时仍会记录本小时调用次数，但不会由 AP 拦截。</small></label><p>Key 使用 Windows 当前用户加密保存，不会回显，也不进入项目档案。保存不会发送收费测试请求。</p><div className="organization-toolbar"><button className="primary-button" disabled={busy}>{busy?'正在保存…':'保存设置'}</button><button type="button" className="secondary-button" onClick={()=>setEditing(false)}>取消</button></div></form>}</section>
    <section className="stats-grid">{[['已确认归类',report?.assignments],['归类变更记录',report?.corrections],['项目档案版本',report?.document_updates],['已回报使用结果',report?.delivery?.reported_outcome_count]].map(([label,value])=><article className="stat-card" key={label}><div><span>{label}</span><strong>{value ?? '…'}</strong><small>记录数量，不代表准确率或认知成熟度</small></div></article>)}</section>
    <section className="page-section"><span className="eyebrow">{project?.display_name || '当前项目'} · 最近可回看的认知过程</span><h2>认知现场</h2>{frames.length?<><div className="organization-toolbar"><label>查看认知帧<select value={Math.min(frameIndex,frames.length-1)} onChange={e=>setFrameIndex(Number(e.target.value))}>{frames.map((_,i)=><option key={i} value={i}>第 {i+1} 帧</option>)}</select></label><span>{frames.length} 个实际保存的帧</span></div><CognitionEvidence frame={frame}/><div className="cognition-live"><article><h3>SA · 这一刻观察到了什么</h3><MessageContent text={frame.sa?.text || '此帧没有可展示的感知文本'} annotations={false}/><small>{({external:'外部活动',readback:'行动结果回读'})[frame.sa?.source] || frame.sa?.source || '来源未记录'} · {({project_activity:'项目活动',text:'文本'})[frame.sa?.modality] || frame.sa?.modality || '类型未记录'}</small></article><article><h3>感受与情绪慢量</h3><div className="feeling-chips">{(frame.feelings||[]).map((f,i)=><span key={i} title={f.name}>{feelingName(f.name)} · {typeof f.intensity === 'number' ? f.intensity.toFixed(3) : '未记录'}</span>)}</div>{slow.length?slow.map(([key,value])=><div className="slow-row" key={key}><span>{NAMES[key]||key}</span><meter aria-label={NAMES[key]||key} min={Math.min(-1,value)} max={Math.max(1,value)} value={value}/><b>{value.toFixed(3)}</b></div>):<p className="muted">当前帧暂无慢量记录。</p>}</article><article><h3>行动候选 · {(frame.actions||[]).length}</h3>{(frame.actions||[]).map((a,i)=><p key={i}><b>{actionName(a.kind || a.action_kind || a.candidate_id)}</b><small className="inline-id">{a.kind || a.action_kind || a.candidate_id}</small> · {typeof a.score === 'number' ? a.score.toFixed(3) : a.total_score ?? '未提供分数'}{a.selected && <span className="evidence-positive"> 已选中</span>}</p>)}<p className="muted">最终选择：{frame.decision?.selected_kind ? actionName(frame.decision.selected_kind) : frame.decision?.selected_candidate_ref || '未选择'}</p></article><article><h3>范式 · {(frame.paradigms||[]).length}</h3>{(frame.paradigms||[]).map((p,i)=><p key={i}>{p.summary || p.pattern_kind || p.paradigm_id || '带来源范式记录'}</p>)}{!frame.paradigms?.length&&<p className="muted">本帧没有范式候选，保留空状态。</p>}</article></div><div className="cognition-readback"><strong>行动结果回读</strong><span>执行结果：{({success:'成功',failed:'失败',partial:'部分完成'})[frame.decision?.result_status] || frame.decision?.result_status || '未记录'}</span><span>结果完整性：{({complete:'完整',partial:'部分',unknown:'未知'})[frame.decision?.result_completeness] || frame.decision?.result_completeness || '未记录'}</span><span>决策归属：{({ap_native:'AP 本地决策',llm:'模型辅助'})[frame.decision?.owner] || frame.decision?.owner || '未记录'}</span></div><TeacherEvidence teacher={episode?.teacher}/></>:<p className="muted">当前项目还没有可展示的认知帧。新活动经过本地运行时后，这里会显示真实保存的 SA、感受、行动与范式。</p>}</section>
    <section className="help-grid">{FEATURES.map(([title,detail,boundary])=><article className="help-card" key={title}><h2>{title}</h2><p>{detail}</p><p>{boundary}</p></article>)}</section>
    <section className="page-section"><h2>怎样判断它真的有帮助？</h2><p>让任务记录“读取了什么、采用了什么、具体减少了哪次重复解释或返工”，再用后续结果复核。当前独立验证收益：<strong>尚未测量</strong>。</p><p className="muted">建议同类任务分别记录基础模式与教师模式的完成率、返工次数、耗时和费用。理论设计提供值得测试的方向，实际收益以这些证据为准。</p><div className="organization-table">{report?.tasks?.map(task=><article key={task.task_id}><div><strong>{task.result?.phase || '已准备整理任务'}</strong><p>{task.total} 条候选 · {new Date(task.created_at).toLocaleString('zh-CN')}</p></div>{task.result?.session_id&&<a href={'codex://threads/'+task.result.session_id}>打开 Codex</a>}</article>)}</div></section>
  </div>;
}
