import {useEffect,useState} from 'react';
import {ArrowClockwise,DownloadSimple} from '@phosphor-icons/react';

const titles={not_checked:'等待下次任务自动检查',checking:'正在检查发行版',current:'已经是当前可用版本',ready:'新版已准备好',installed:'新版已安装',busy:'等工作空闲后安装',pending:'等待安装',development_changes:'当前为开发环境，保留本地改动',release_not_packaged:'当前发行版暂无自动安装包',check_failed:'本次检查未完成，稍后自动重试',rolled_back:'新版启动失败，已恢复原版入口',disabled:'自动更新已关闭',no_release:'暂无可用发行版',unmanaged:'此服务未由安装器管理'};
async function api(body){const r=await fetch('/v1/ap-vibe/updates',{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok||v.ok===false)throw Error(v.error?.message||v.error?.code||'暂时无法读取更新状态');return v;}
export function WorkbenchUpdates(){
  const [data,setData]=useState(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{let live=true,timer;const poll=async()=>{try{const v=await api();if(live){setData(v);setError('');}}catch(e){if(live)setError(e.message);}if(live)timer=setTimeout(poll,open?4000:30000);};poll();return()=>{live=false;clearTimeout(timer);};},[open]);
  async function act(body){setBusy(true);setError('');try{const v=await api(body);setData(v);setNotice(v.requested?'已安排后台检查，你可以继续使用。':'更新偏好已保存。');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <details className="workbench-updates" onToggle={e=>setOpen(e.currentTarget.open)}><summary><DownloadSimple size={15}/><span>版本与自动更新</span><small>{data?.current_version||'本机安装'}</small></summary>{open&&<div className="update-content"><div><strong>{data?titles[data.state]||'正在等待更新结果':'正在读取更新状态…'}</strong>{data?.available_version&&<p>可用发行版：{data.available_version}</p>}<p>新任务会自动检查更新，空闲时安装。项目档案、伙伴配置和历史保存在原位置；新版启动失败会尝试恢复原版。</p>{data?.message&&<p>{data.message}</p>}{data?.checked_at&&<small>最近检查：{new Date(data.checked_at*1000).toLocaleString('zh-CN')}</small>}</div>{data?.available&&<div className="update-controls"><label>更新方式<select disabled={busy} value={data.mode} onChange={e=>act({action:'configure',mode:e.target.value,channel:data.channel})}><option value="automatic">自动检查，空闲安装（推荐）</option><option value="check">只检查并准备新版</option><option value="off">关闭自动更新</option></select></label><label>接收版本<select disabled={busy} value={data.channel} onChange={e=>act({action:'configure',mode:data.mode,channel:e.target.value})}><option value="beta">内测版与正式版</option><option value="stable">仅正式版</option></select></label><button className="secondary-button" disabled={busy||data.mode==='off'} onClick={()=>act({action:'check'})}><ArrowClockwise size={16}/>{busy?'正在安排…':'现在检查'}</button></div>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{data?.integration_issues?.length>0&&<p>服务已更新，部分 Skills 同步未完成：{data.integration_issues.join('、')}。可请 Codex 修复安装集成。</p>}</div>}</details>;
}
